# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Sanjana Krishnamurthy
tagline:          'My little world.'
description:      'Passionate, Creative, Conversational'
url:              https://sxnjanak.github.io
baseurl:          /

author:
  name:           'Sanjana Krishnamurthy'
  url:            'https://sxnjanak.github.io'

paginate:         5

# Custom vars
version:          0.1.0

github:
  account:           https://github.com/sxnjanak

resume:          'public/assets/Sanjana_K_Resume.pdf'
