# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Sanjana's World
tagline:          'My little world.'
description:      'A personal blog by Sanjana Krishnamurthy.'
url:              https://sxnjanak.github.io
baseurl:          /

author:
  name:           'Sanjana Krishnamurthy'
  url:            'https://sxnjanak.github.io'

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/sxnjanak/sxnjanak.github.io
